### ISSUE TITLE
 Error determining zone_id: 401 - default timezone issue

### ISSUE THREAD

**Issue by mentoRisen** [Mordred/certbot-plugin-websupport#5]
I was getting error `Error determining zone_id: 401` and I was sure that I have credential correct. I tested few api calls on the other project and it worked. I compared your code with websupport examples, and find out that you don't explicitly set timezone in Date header. I think somehow my default timezone was messed up. Anyway, I changed line 208 in dns.py from
`"Date": datetime.fromtimestamp(timestamp).isoformat()`
to 
`"Date": datetime.fromtimestamp(timestamp, timezone.utc).isoformat() `
and added import for timezone and it started working. 
Probably add this fix to repository.

**Comment by Mordred** [comment]
Please create a PR :) Thanks
